services:
  api:
    build:
      context: ./api
    ports:
      - 5000:5000
    env_file: .env
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - db

  app:
    build:
      context: ./app
    ports:
      - 3000:3000
    env_file: .env
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - api      

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./minical/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./minical:/app
    links:
      - php

  php:
    build:
      context: ./minical
      target: base
    volumes:
      - ./minical:/app
    links:
      - db
      - composer

  db:
    image: mariadb:latest
    env_file: .env
    volumes:
      - mysqldata:/var/lib/mysql

  composer:
    image: composer:latest
    command: ["composer", "install"]
    volumes:
      - ./minical:/app

volumes:
  mysqldata: {}
